### ISSUE TITLE
Restaurar rama 'Desarollo' al estado inicial (primer commit) - Autor: Miguel, Rama: Propuestas

### ISSUE THREAD

**Issue by miguelmurga** [Github-ABRIL/NuxtFront#3]
Descripción:
Necesito restaurar la carpeta 'Desarollo' y la rama 'Propuestas' a sus estados iniciales respectivos. La rama 'Desarollo' debe volver al primer commit, mientras que la rama 'Propuestas' debe regresar al commit "Primer propuesta chat en json".

**Comment by paloarella** [comment]
GLORIA@DESKTOP-SB7KE8L MINGW64 /c/repo (propuestas)
$ git checkout desarrollo
Switched to branch 'desarrollo'
Your branch is behind 'origin/desarrollo' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

GLORIA@DESKTOP-SB7KE8L MINGW64 /c/repo (desarrollo)
$ git reset --hard e4609da
HEAD is now at e4609da primer commit de mi repositorio

GLORIA@DESKTOP-SB7KE8L MINGW64 /c/repo (desarrollo)
$ git checkout propuestas
Switched to branch 'propuestas'
Your branch is up to date with 'origin/propuestas'.

GLORIA@DESKTOP-SB7KE8L MINGW64 /c/repo (propuestas)
$ git log --oneline
88a9b72 (HEAD -> propuestas, origin/propuestas) Primer propuesta chat en json
b9722aa Primer propuesta chat en json
95e51a0 (origin/main, origin/desarrollo, main) agregar texto
5b9b2dd segundo commit de mi repositorio
e4609da (desarrollo) primer commit de mi repositorio

GLORIA@DESKTOP-SB7KE8L MINGW64 /c/repo (propuestas)
$ git reset --hard b9722aa
HEAD is now at b9722aa Primer propuesta chat en json

GLORIA@DESKTOP-SB7KE8L MINGW64 /c/repo (propuestas)
$ git push --force
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
To https://github.com/paloarella/repo-1.git
 + 88a9b72...b9722aa propuestas -> propuestas (forced update)
